export const data = [
    {
        id: 12,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
    {
        id: 13,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
    {
        id: 11,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
    {
        id: 9,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
    {
        id: 10,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
    {
        id: 8,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
    {
        id: 6,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
    {
        id: 7,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
    {
        id: 4,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
    {
        id: 5,
        usuario_id: 2,
        nome: "teste",
        valor: 0,
        categoria: "teste",
        tipo: "saida",
        data: "2025/12/10",
    },
];
